# Generated by Django 3.2.8 on 2022-02-08 10:17

import core.utils
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petowner',
            name='pet',
        ),
        migrations.AddField(
            model_name='pet',
            name='owner',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, to='pet.petowner', verbose_name='Pet Owner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='petowner',
            name='email',
            field=models.EmailField(default=True, max_length=254, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='email address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='petowner',
            name='phone',
            field=models.CharField(default=True, help_text='Phone number must be entered in the format: +901234567890. ', max_length=20, validators=[core.utils.PhoneNumberValidator()], verbose_name='Phone Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='petowner',
            name='surname',
            field=models.CharField(default=True, max_length=100, verbose_name='PetOwner SurName'),
            preserve_default=False,
        ),
    ]
