# Generated by Django 3.2.8 on 2022-02-08 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_auto_20220208_1317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petowner',
            old_name='name',
            new_name='name1',
        ),
    ]
